field.widget.settings.strava_route_widget:
  type: mapping
  label: 'Strava Route widget settings'
  mapping: {}

strava_api.settings:
  type: config_object
  label: 'Strava API settings'
  mapping:
    access_token:
      type: string
      label: 'Strava API access token'
    refresh_token:
      type: string
      label: 'Strava OAuth refresh token'
    token_expires:
      type: integer
      label: 'Access token expiry (Unix timestamp)'
    client_id:
      type: string
      label: 'Strava OAuth Client ID'
    client_secret:
      type: string
      label: 'Strava OAuth Client Secret'
    map_height:
      type: string
      label: 'Default map height (CSS value)'
    map_style:
      type: string
      label: 'Map style'
    show_elevation:
      type: boolean
      label: 'Show elevation profile'
